### ISSUE TITLE
Homebrew Formula?

### ISSUE THREAD

**Issue by Olshansk** [mgdm/htmlq#12]
Is there a brew formula available to install this?

**Comment by NikolayMurha** [comment]
https://github.com/Homebrew/homebrew-core/pull/84809

**Comment by NikolayMurha** [comment]
@mgdm Due this comments we should apply tag to release.
Could you make release please? 

https://github.com/Homebrew/homebrew-core/pull/84809#pullrequestreview-748091578
https://github.com/Homebrew/homebrew-core/pull/84809#discussion_r703511626

**Comment by NikolayMurha** [comment]
I made homebrew formula, but I think the project is not active. The author does not accept pull requests and does not respond to issues.

**Comment by jasonbosco** [comment]
I spoke to the author and he said he’ll take a look at the PRs at the end of his work day.

**Comment by mgdm** [comment]
Hi! Thanks for doing that I'm evaluating another PR and once I decide what to do with it I'll tag the release.

**Comment by chenrui333** [comment]
Thanks @mgdm!

**Comment by NikolayMurha** [comment]
Congratulations! The formula is merged!

**Comment by gingerhot** [comment]
I see the installation still depends on `cargo`, could we just install it in binary? That will be convenient for those who just hope for a command tool and have not a Rust environment. Hope I didn't misunderstand the formula configuration.

Add if we could upload the binaries in releases, that will be easy for people to install by platform manually.

**Comment by NikolayMurha** [comment]
@gingerhot If we are talking about Homebrew Formula, Homebrew build binaries  for different environments, so this is not a big problem. 
In most cases, the buildfrom sources is not run on the client's machine. 
In addition, rust is installed as a dependency only for build phase. For other platforms, a binary releases would be better.
I hope I understood the essence of the question correctly. Please note that I do not develop in rust and do not know all the nuances of distributing code in this environment.

**Comment by gingerhot** [comment]
> @gingerhot If we are talking about Homebrew Formula, Homebrew build binaries for different environments, so this is not a big problem.
> In most cases, the buildfrom sources is not run on the client's machine.
> In addition, rust is installed as a dependency only for build phase. For other platforms, a binary releases would be better.
> I hope I understood the essence of the question correctly. Please note that I do not develop in rust and do not know all the nuances of distributing code in this environment.

So that is no problem with it. Thank you for your answering.

**Comment by HelloRusk** [comment]
Now that we can install this with Homebrew, why not write about it on README?

**Comment by Olshansk** [comment]
@HelloRusk Looks like it's already there:  curl --silent https://www.rust-lang.org/ | htmlq --attribute href a

I just installed it with `brew install htmlq` and everything works flawlessly. Thank you!

**Comment by HelloRusk** [comment]
@Olshansk Oh yes, it was in this commit https://github.com/mgdm/htmlq/commit/014ae255b9230d03a0e9dda959796ef997eff5fd
