### ISSUE TITLE
Add option for converting relative href to absolute.

### ISSUE THREAD

**Issue by Chaz6** [mgdm/htmlq#13]
In the example `curl -s https://www.rust-lang.org/ | htmlq -a href a` the links are output as-is, for example, `/policies`. In order to use this with other tools, it would be useful to make these links absolute. For example, `curl -s https://www.rust-lang.org/ | htmlq -u https://www.rust-lang.org/ -a href a` would results in `https://www.rust-lang.org/policies` (i.e. any relative href attributes are converted to absolute using the base url specified with `-u`).

**Comment by lordmauve** [comment]
Note that this also has to honour the [<base href>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) element if present.

**Comment by marceloboeira** [comment]
It would be interesting o check if that is an option already for the HTML parser/manipulation library, if it is we could just pipe the option to the parser if not we would have to build around it.

https://github.com/servo/html5ever

**Comment by mgdm** [comment]
I've added a PR from the `base_urls` branch that does this, if you'd like to try it out.

`htmlq --base https://example.org` will rewrite relative URLs according to that URL.
`htmlq --detect-base` will try to find a base URL from the `<base>` element in the document. If not found, don't rewrite.

If you specify both, it will default to the base in the document, and fall back to the one supplied for `--base` if not found.

**Comment by yermulnik** [comment]
Apologies for bumping old closed issue, though I'm trying to figure out whether it's me doing something incorrect, or this isn't supported by `htmlq`:
```shell
> curl -SsL https://www.d[…].ua/ua/shutdowns --cookie /tmp/cookies.txt | htmlq 'html body div.wrapper div.content main.main section.section.section--no-padding.section-class-35 .container figure picture img' --attribute src --base https://www.d[…].ua
/media/page/page-chart-9167-1050.png
/media/page/page-chart-9170-1050.png
```
I'd expect the output to be absolute URLs. Am I wrong?
Thanks.

**Comment by yermulnik** [comment]
@mgdm
