### ISSUE TITLE
Add Windows Support

### ISSUE THREAD

**Issue by dmoath** [mgdm/htmlq#16]
Tried to install this under windows (not WSL2) and it fails to compile:

```
error: failed to build archive: function not supported

error: aborting due to previous error

error: could not compile `rand_core`

```

Any chance you could add Windows support or just release a windows binary?

**Comment by kassemz** [comment]
@dmoath 

It installs fine for me on Windows 10.

Find binary attached here if it helps.
[htmlq-0.0.1.zip](https://github.com/mgdm/htmlq/files/7131092/htmlq-0.0.1.zip)

**Comment by dmoath** [comment]
@kassemz  Thanks, I was able to compile it in a VM, I guess having multiple versions of VC++ installed can affect rustc somehow, weird thing is other (complex) programs compile just fine, it's just this one dependency "rand_core".
