### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by Aeres-u99** [mgdm/htmlq#3]
I will truly appreciate an invert selector, something which will display everything else other than that.
It will be very useful for excluding and remove weird javascript and google ads

**Comment by mazznoer** [comment]
Maybe `--remove` flag.

```
htmlq -f file.html --remove 'script' > clean.html
```

It will remove all selected elements, and output everything else. It will be very useful.

**Comment by Aeres-u99** [comment]
Thanks a lot!

**Comment by danimesq** [comment]
@mazznoer, is it possible to [append or change the content inside a tag id](https://github.com/mgdm/htmlq/issues/33)
