### ISSUE TITLE
Improving the `-B` logic

### ISSUE THREAD

**Issue by ralyodio** [mgdm/htmlq#32]
Most sites will not have a `<base...>` element. Is there anyway to ascertain the domain it came from? I guess not huh if we're piping from curl output. Maybe use tee to pass domain and body?

**Comment by mgdm** [comment]
It's not really something I can think of a great solution for. If you're doing some kind of automation that downloads from a particular website using `curl` or similar, I'd hope you could extend it to be able to pass the `--base` option to `htmlq`.
