### ISSUE TITLE
Binary release

### ISSUE THREAD

**Issue by piranha** [mgdm/htmlq#6]
Hey, it would be nice to be able to just download a binary without setting up complete Rust toolchain. :-)

**Comment by c33s** [comment]
is there an eta on this?

**Comment by c33s** [comment]
please reopen, there are no binaries to download yet (also looking for windows binaries #16)

![image](https://user-images.githubusercontent.com/649209/132519984-2ceac504-6daa-4175-8fc3-acfe783f9ca0.png)

**Comment by immanuelfodor** [comment]
I was also looking for a binary release, found this issue among the closed ones. Why don't you provide a binary? 

Here is a nice example: https://github.com/sharkdp/bat/releases/tag/v0.18.3

I'd love to have x86_64 Linux GNU and musl releases from this tool.

**Comment by mgdm** [comment]
Hi! This was closed when I merged the PR to add the GitHub Actions to do the build, which referenced this one. Turns out something didn't quite work out, but I've not had the time to debug it yet. It's still something I definitely want to sort out - will try and have a look soon.
