### ISSUE TITLE
Selecting an arbitrary property in tags

### ISSUE THREAD

**Issue by jtagcat** [mgdm/htmlq#60]
Sometimes there isn't much to reference in HTML, but elements do still have something like `<div data-testid="foobar">`. As far as I know, htmlq doesn't have anything to handle this, or does it? If not, how could it be implemented?

**Comment by dylanstee-db** [comment]
You can use [CSS attribute selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors). In your case, you could do

```sh
htmlq '[data-testid="foobar"]'
```
