### ISSUE TITLE
How to install this

### ISSUE THREAD

**Issue by alexanderkoponen** [mgdm/htmlq#8]
Could you please write a couple of lines, in the README.md how one can download, compile and install this?
As it is now, I believe that only a Rust native knows how to install this.

**Comment by infostreams** [comment]
I just want to do ```brew install htmlq``` to be honest...

**Comment by esamattis** [comment]
Install Rust tools https://www.rust-lang.org/learn/get-started

Eg. on macOS run

```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

Open new terminal 

```
git clone https://github.com/mgdm/htmlq.git
cd htmlq
cargo build --release
```

And you'll find the binary from `target/release/htmlq`

**Comment by infostreams** [comment]
I got one of my own repositories accepted into Homebrew, but it wasn't as straightforward as I'd hoped. Here's some text on how it can be achieved by (apparently) adding a single file into the repository: https://rust-cli.github.io/book/tutorial/packaging.html#getting-your-app-into-package-repositories

**Comment by antibland** [comment]
On macOS, I followed the instructions detailed above, and restarted my shell. I then tried running one of the examples:

```
$ curl -s https://www.rust-lang.org/ | htmlq '#get-help'
```

But am seeing this:

```
zsh: command not found: htmlq
```
